# Define the pre-commit hooks that will be established with pip's 'pre-commit' package.
# https://pre-commit.com/
# NOTE: we define individual tool rules in pyproject.toml to be consistent in CI and local PCs.

# TODO: always double-check that we are using the same versions in requirements.txt!

default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/pylint
    rev: v2.9.1
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=100"]
  - repo: local
    hooks:
      - id: branch-name-enforcement
        name: branch-name-enforcement
        language: python
        stages: [push]
        entry: hooks/enforce_branch_name.py
